#!/bin/bash
NAME=$1
if ! [ $NOTEBOOK_HOME ]; then
    NOTEBOOK_HOME=$HOME
fi
WORK_HOME=/home/jovyan/work
ENTRYPOINT=jupyter-notebook
ENTRYPOINT_ARGS="--ip=0.0.0.0 --NotebookApp.token=\"\" --NotebookApp.disable_check_xsrf=True"
HOST_PORT=8887 # Open port on the host machine.  
if [ "$2" = "-dev" ]; then
  docker run -it --entrypoint=$ENTRYPOINT \
   -v $SCIDASH_HOME/sciunit:$WORK_HOME/sciunit \
   -v $SCIDASH_HOME/neuronunit:$WORK_HOME/neuronunit \
   -p $HOST_PORT:8888 -v $NOTEBOOK_HOME:$WORK_HOME \
   scidash/$NAME $ENTRYPOINT_ARGS
else
  docker run -it --entrypoint=$ENTRYPOINT \
  -p $HOST_PORT:8888 -v $NOTEBOOK_HOME:$WORK_HOME \
  scidash/$NAME $ENTRYPOINT_ARGS
fi

# Now access the notebook server at http://localhost:$HOST_PORT